# github repository Actions íŽ˜ì´ì§€ì— ë‚˜íƒ€ë‚¼ ì´ë¦„..
name: soullive A CI/CD with Gradle

# event trigger
# main, develop ë¸Œëžœì¹˜ì— push ì‹œì‹¤í–‰ë˜ëŠ” íŠ¸ë¦¬ê±°
on:
  # í‘¸ì‹œí–ˆì„ ë•Œ ci/cd
  push:
    branches: [ "main", "develop" ]

# permissions: write-all


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      ## jdk setting
      - uses: actions/checkout@v3
      - name: ðŸ§Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle caching
      - name: ðŸ§Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ðŸ§gradle buildë¥¼ ìœ„í•œ ê¶Œí•œì„ ë¶€ì—¬í•©ë‹ˆë‹¤.
        run: chmod +x gradlew

      - name: ðŸ§gradle build ì¤‘ìž…ë‹ˆë‹¤.
        run: ./gradlew build
        shell: bash # ciëŠ” ì—¬ê¸°ê¹Œì§€

      - name: ðŸ§docker image build í›„ docker hubì— pushí•©ë‹ˆë‹¤.
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      ## deploy to production
      - name:  docker hubì—ì„œ pull í›„ deployí•©ë‹ˆë‹¤.
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_USERNAME }}
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
            sudo docker stop $(sudo docker ps -q) 2>/dev/null || true
            sudo docker run --rm -d --network='host' -p 80:8080 --name ${{ secrets.DOCKER_IMAGE }} \
            -e RDB_HOST=${{ secrets.RDB_HOST }} \
            -e RDB_PORT=${{ secrets.RDB_PORT }} \
            -e RDB_SCHEMA=${{ secrets.RDB_SCHEMA }} \
            -e RDB_USER=${{ secrets.RDB_USER }} \
            -e RDB_PASSWORD=${{ secrets.RDB_PASSWORD }} \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
            sudo docker system prune -f
